INCLUDE ~%COMPONENT_FOLDER%/rules_adjustments.tpa~
INCLUDE ~%COMPONENT_FOLDER%/companions_adjustments.tpa~

LAF APPLY_RULES_ADJUSTMENTS RET_ARRAY hpclass_table 
    hp_lvl1_values 
    hp_static_increment_values 
    END
LAF APPLY_COMPANIONS_ADJUSTMENTS STR_VAR hpclass_table_ref = hpclass_table 
    hp_lvl1_values_ref = hp_lvl1_values
    hp_static_increment_values_ref = hp_static_increment_values
    END
