DEFINE_ACTION_FUNCTION APPLY_STATDESC_ENTRY 
    INT_VAR str_ref = ~~
    STR_VAR icon = 0
    RET entry
BEGIN 
    COPY_EXISTING ~statdesc.2da~ ~override~
        LPF READ_2DA_ROW_NAMES RET_ARRAY entries = out END
        SET last_entry = 0
        PHP_EACH entries AS entry => _ BEGIN 
            SET last_entry = entry
        END

        SET entry = last_entry + 1
        LPF INSERT_2DA_ROW_VALUE STR_VAR row_value = ~%entry% %str_ref% %icon%~ END
        BUT_ONLY
END
