IF
    OnCreation()
    !HasItem("dbfchrr", Player1)
THEN
    RESPONSE #100
        GiveItemCreate("dbfchrr", Player1, 0, 0, 0)
        XEquipItem("dbfchrr", Player1, SLOT_RING_RIGHT, EQUIP)
        Continue()
END

IF
    OnCreation()
    HasItem("dbfchrr", Player1)
    !HasItemEquiped("dbfchrr", Player1)
THEN
    RESPONSE #100
        XEquipItem("dbfchrr", Player1, SLOT_RING_RIGHT, EQUIP)
        Continue()
END
