DEFINE_ACTION_FUNCTION APPLY_RESPAWN_TRIGGER
    STR_VAR respawn_execution_cutscene = 0
BEGIN
    <<<<<<<< .../respawn_trigger.baf
    IF
        HP(Player1, 1)
    THEN
        RESPONSE #100
            ClearAllActions()
            StartCutSceneMode()
            StartCutSceneEx("%respawn_execution_cutscene%", TRUE)
    END
    >>>>>>>>

    EXTEND_BOTTOM ~baldur.bcs~ ~.../respawn_trigger.baf~ 
        EVALUATE_BUFFER
END
